development:
  adapter: postgresql
  encoding: unicode
  database: students_development
  pool: 2
  username: postgres
  password: 191703
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: students_production
  pool: 2
  username: postgres
  password: 191703
  host: localhost